# Generated by Django 5.2.8 on 2025-11-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
