# Generated by Django 4.2.27 on 2026-01-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_booking_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('cubicle_code', models.CharField(default='NOSTP 02 16 A 001', max_length=100)),
                ('location', models.CharField(default='Noida, NOSTP, BHUT01, FLOOR-16, A', max_length=255)),
                ('slot_start', models.CharField(default='08:00AM', max_length=10)),
                ('slot_end', models.CharField(default='02:00PM', max_length=10)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
